development:
  adapter: postgresql
  encoding: unicode
  database: parc_development
  pool: 5
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: prac_test
  pool: 5
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: prac_production
  pool: 5
  template: template0
